/* Storybook reader.  Story text comes from story.js (window.STORY). */
(function () {
  'use strict';

  /* ---------------- Parsing ---------------- */

  const KEY_RE = /^(image|alt|caption|chapter)\s*:\s*(.*)$/i;
  const FLAG_RE = /^(contents|blank|center)\s*$/i;

  function smartQuotes(s) {
    return s
      .replace(/(^|[\s(\[{—-])"/g, '$1“').replace(/"/g, '”')
      .replace(/(^|[\s(\[{—-])'/g, '$1‘').replace(/'/g, '’');
  }

  function parseStory(src) {
    const story = { title: 'Untitled', author: '', artist: '', cover: '', pages: [] };
    const sections = String(src).replace(/\r\n?/g, '\n').split(/^[ \t]*-{3,}[ \t]*$/m);

    // Front matter: "key: value" lines before the first ---
    for (const line of sections.shift().split('\n')) {
      const m = line.match(/^\s*([\w-]+)\s*:\s*(.*)$/);
      if (m) story[m[1].toLowerCase().replace('-', '')] = m[2].trim();
    }
    story.pages.push({ kind: 'cover', title: story.title, author: story.author, artist: story.artist, image: story.coverimage || story.cover || '' });

    for (const sec of sections) {
      const page = { kind: 'page', blocks: [], center: false };
      let para = [];
      let lastImage = null;
      const flush = () => {
        if (para.length) page.blocks.push({ type: 'text', text: smartQuotes(para.join(' ')) });
        para = [];
      };
      for (const raw of sec.split('\n')) {
        const line = raw.trim();
        let m;
        if (!line) { flush(); continue; }
        if ((m = line.match(FLAG_RE))) {
          const f = m[1].toLowerCase();
          if (f === 'center') page.center = true;
          else page.kind = f;                       // contents | blank
          continue;
        }
        if ((m = line.match(KEY_RE))) {
          const key = m[1].toLowerCase(), val = m[2].trim();
          if (key === 'image') {
            flush();
            lastImage = { type: 'image', src: val, alt: '', caption: '' };
            page.blocks.push(lastImage);
          } else if (key === 'alt' && lastImage) lastImage.alt = val;
          else if (key === 'caption' && lastImage) lastImage.caption = smartQuotes(val);
          else if (key === 'chapter') { flush(); page.kind = 'chapter'; page.chapter = val; }
          continue;
        }
        para.push(line.replace(/^\\/, ''));       // "\image: ..." escapes a keyword
      }
      flush();
      const empty = page.kind === 'page' && !page.blocks.length;
      if (!empty) story.pages.push(page);
    }
    return story;
  }

  /* ---------------- Rendering ---------------- */

  function el(tag, cls, text) {
    const e = document.createElement(tag);
    if (cls) e.className = cls;
    if (text != null) e.textContent = text;
    return e;
  }

  // "[link text](https://example.com)" becomes a real <a>. Only http(s) and
  // mailto links are allowed, so odd story text can't smuggle in javascript: etc.
  // Link text may itself contain one level of [bracketed] text, e.g. a name
  // like "PHASEONE[big]".
  const LINK_RE = /\[((?:[^\[\]]|\[[^\[\]]*\])+)\]\((https?:\/\/[^\s()]+|mailto:[^\s()]+)\)/g;

  function elText(tag, cls, text) {
    const e = document.createElement(tag);
    if (cls) e.className = cls;
    LINK_RE.lastIndex = 0;
    let last = 0, m;
    while ((m = LINK_RE.exec(text))) {
      if (m.index > last) e.appendChild(document.createTextNode(text.slice(last, m.index)));
      const a = el('a', null, m[1]);
      a.href = m[2];
      a.target = '_blank';
      a.rel = 'noopener noreferrer';
      e.appendChild(a);
      last = LINK_RE.lastIndex;
    }
    if (last < text.length) e.appendChild(document.createTextNode(text.slice(last)));
    return e;
  }

  // Pixel size of each illustration (generated by tools/make-web-images.py),
  // so a page can be laid out before its picture arrives.
  const IMAGE_SIZES = window.IMAGE_SIZES || {};

  function renderImage(block) {
    const fig = el('figure');
    const dims = IMAGE_SIZES[block.src];
    if (measuring && dims) {
      // The measuring pass only needs the picture's footprint, so stand in a
      // box of the right proportions instead of fetching every illustration
      // in the book up front.
      const box = el('div', 'img-placeholder');
      box.style.aspectRatio = dims[0] + ' / ' + dims[1];
      fig.appendChild(box);
    } else {
      const img = el('img');
      if (dims) { img.width = dims[0]; img.height = dims[1]; }
      img.src = block.src;
      img.alt = block.alt || block.caption || 'Illustration';
      img.draggable = false;
      if (!measuring) img.addEventListener('load', scheduleRefit);   // live images only, never the measuring pass
      img.addEventListener('error', () => {
        fig.replaceChild(el('div', 'missing', 'Missing illustration: ' + block.src), img);
      });
      fig.appendChild(img);
    }
    if (block.caption) fig.appendChild(elText('figcaption', null, block.caption));
    return fig;
  }

  function renderPage(story, index) {
    const page = story.pages[index];
    const root = el('div', 'page-content');
    const cover = story.pages[0];

    // In a two-page spread the cover art fills the left page opposite the title.
    if (index === -1 && mode === 'spread' && cover && cover.image) {
      root.classList.add('cover-art');
      root.appendChild(renderImage({ src: cover.image, alt: cover.title }));
      return root;
    }

    if (!page || page.kind === 'blank') { root.classList.add('blank'); return root; }

    if (page.kind === 'cover') {
      root.classList.add('cover');
      if (page.image && mode !== 'spread') root.appendChild(renderImage({ src: page.image, alt: page.title }));
      root.appendChild(el('h1', 'title', page.title));
      root.appendChild(el('hr', 'rule'));
      if (page.author) root.appendChild(elText('p', 'author', page.author));
      if (page.artist) root.appendChild(elText('p', 'artist', page.artist));
      return root;
    }

    if (page.kind === 'chapter') {
      root.classList.add('chapter');
      const chapters = story.pages.filter(p => p.kind === 'chapter');
      const n = chapters.indexOf(page) + 1;
      if (chapters.length > 1) root.appendChild(el('div', 'kicker', 'Chapter ' + n));
      root.appendChild(el('h2', null, page.chapter));
      root.appendChild(el('hr', 'rule'));
      for (const b of page.blocks) root.appendChild(b.type === 'image' ? renderImage(b) : elText('p', null, b.text));
      return root;
    }

    if (page.kind === 'contents') {
      root.classList.add('contents');
      root.appendChild(el('h2', null, 'Contents'));
      const ol = el('ol');
      story.pages.forEach((p, i) => {
        if (p.kind !== 'chapter') return;
        const li = el('li');
        li.appendChild(el('span', 'name', p.chapter));
        li.appendChild(el('span', 'dots'));
        li.appendChild(el('span', 'num', String(i)));
        li.dataset.goto = i;
        ol.appendChild(li);
      });
      root.appendChild(ol);
      return root;
    }

    // ordinary page
    const hasText = page.blocks.some(b => b.type === 'text');
    const hasImg = page.blocks.some(b => b.type === 'image');
    if (hasText) root.classList.add('has-text');
    if (hasImg && !hasText) root.classList.add('image-only');
    if (page.center) root.classList.add('center');
    for (const b of page.blocks) root.appendChild(b.type === 'image' ? renderImage(b) : elText('p', null, b.text));
    return root;
  }

  // ---- Uniform font scale ----
  // A real book uses one type size throughout, so instead of shrinking pages
  // individually we find the largest scale (<= 1) at which EVERY text page
  // fits, and apply it to the whole book via the --fs-scale CSS variable.
  let fsScale = 1;
  let measureEl = null;
  let measuring = false;

  function computeScale(story, book) {
    if (!measureEl) {
      measureEl = el('div', 'page measure');
      measureEl.setAttribute('aria-hidden', 'true');
      book.appendChild(measureEl);
    }
    let scale = 1;
    const tooLong = [];
    measuring = true;
    for (let i = 0; i < story.pages.length; i++) {
      const pg = story.pages[i];
      if (!pg || pg.kind !== 'page' || !pg.blocks.some(b => b.type === 'text')) continue;
      measureEl.replaceChildren(renderPage(story, i));
      const c = measureEl.firstChild;
      const overflows = () => c.scrollHeight > c.clientHeight + 1;
      c.style.setProperty('--fs-scale', scale);
      while (overflows() && scale > 0.6) {
        scale = Math.round((scale - 0.02) * 100) / 100;
        c.style.setProperty('--fs-scale', scale);
      }
      if (overflows()) tooLong.push(i);
    }
    measureEl.replaceChildren();
    measuring = false;
    if (tooLong.length) console.warn('Storybook: too much text to fit on page(s) ' + tooLong.join(', ') + '. Consider splitting them.');
    return scale;
  }

  function fill(container, story, index) {
    container.replaceChildren();
    const content = renderPage(story, index);
    container.appendChild(content);
    const page = story.pages[index];
    if (page && index > 0 && page.kind !== 'blank' && page.kind !== 'chapter' && page.kind !== 'contents') {
      container.appendChild(el('div', 'page-number', String(index)));
    }
    return content;
  }

  /* ---------------- Reader state ---------------- */

  const story = parseStory(window.STORY || '');
  const N = story.pages.length;
  const book = document.getElementById('book');
  const pageL = document.getElementById('pageL');
  const pageR = document.getElementById('pageR');
  const status = document.getElementById('status');
  const btnPrev = document.getElementById('btnPrev');
  const btnNext = document.getElementById('btnNext');

  document.title = story.title;

  let mode = 'single';    // 'single' | 'spread'
  let cur = 0;            // single: the page shown.  spread: the RIGHT page (always even; left is cur-1)
  let turning = false;

  function clamp(i) { return Math.max(0, Math.min(N - 1, i)); }
  function spreadRight(i) { return 2 * Math.ceil(i / 2); }

  function canNext() { return mode === 'spread' ? cur + 1 < N : cur + 1 < N; }
  function canPrev() { return mode === 'spread' ? cur >= 2 : cur >= 1; }

  function updateChrome() {
    btnPrev.disabled = !canPrev();
    btnNext.disabled = !canNext();
    let where;
    if (mode === 'spread') {
      const l = cur - 1, r = cur;
      const lOk = l >= 1, rOk = r >= 1 && r < N;
      where = lOk && rOk ? `Pages ${l}–${r}` : lOk ? `Page ${l}` : rOk ? `Page ${r}` : 'Cover';
    } else {
      where = cur === 0 ? 'Cover' : `Page ${cur}`;
    }
    if (!status.querySelector('.jump')) {         // don't clobber a page number being typed
      const whereBtn = el('button', 'where', `${where} of ${N - 1}`);
      whereBtn.type = 'button';
      whereBtn.title = 'Jump to a page (G)';
      whereBtn.addEventListener('click', openJump);
      status.replaceChildren(el('span', 'title', story.title), el('span', 'sep', '·'), whereBtn);
    }
    // The address bar is never rewritten as the reader turns pages, so copying
    // the URL shares the book from the cover, not whatever page they stopped on.
    // A "#p7" deep link stays in the URL only while page 7 is actually showing;
    // once the reader moves on it is dropped rather than left pointing at a stale page.
    const linked = location.hash.match(/^#p(\d+)$/);
    if (linked && !isShowing(+linked[1])) {
      history.replaceState(null, '', location.pathname + location.search);
    }
  }

  // Clicking the "Page X of N" indicator (or pressing G) swaps it for a
  // number box; Enter jumps there, Escape or clicking away cancels.
  function openJump() {
    const whereBtn = status.querySelector('.where');
    if (!whereBtn) return;
    const form = el('form', 'jump');
    const input = el('input');
    input.type = 'number';
    input.inputMode = 'numeric';
    input.min = 0;
    input.max = N - 1;
    input.value = mode === 'spread' ? Math.max(1, cur - 1) : cur;
    input.setAttribute('aria-label', `Page number, 0 to ${N - 1}`);
    form.append(el('span', null, 'Page '), input, el('span', null, ` of ${N - 1}`));
    let closed = false;
    const close = () => {
      if (closed) return;
      closed = true;
      form.remove();
      updateChrome();
    };
    form.addEventListener('submit', (e) => {
      e.preventDefault();
      const n = parseInt(input.value, 10);
      closed = true;
      form.remove();
      if (Number.isFinite(n)) goTo(n); else updateChrome();
    });
    input.addEventListener('keydown', (e) => { if (e.key === 'Escape') { e.preventDefault(); close(); } });
    input.addEventListener('blur', close);
    whereBtn.replaceWith(form);
    input.focus();
    input.select();
  }

  function isShowing(i) { return i === cur || (mode === 'spread' && i === cur - 1); }

  function render() {
    if (mode === 'spread') {
      fill(pageL, story, cur - 1);
      fill(pageR, story, cur);
    } else {
      fill(pageR, story, cur);
    }
    updateChrome();
    prefetchNeighbours();
  }

  // Fetch the pictures on the next and previous spreads in the background so
  // they are already cached when the page turns.
  const prefetched = new Set();
  function prefetchNeighbours() {
    const around = mode === 'spread' ? [cur + 1, cur + 2, cur - 3, cur - 2] : [cur + 1, cur - 1];
    for (const i of around) {
      const pg = story.pages[i];
      if (!pg) continue;
      const srcs = [];
      if (pg.image) srcs.push(pg.image);
      if (pg.blocks) for (const b of pg.blocks) if (b.type === 'image') srcs.push(b.src);
      for (const src of srcs) {
        if (prefetched.has(src)) continue;
        prefetched.add(src);
        new Image().src = src;
      }
    }
  }

  function goTo(i) {
    i = clamp(i);
    cur = mode === 'spread' ? spreadRight(i) : i;
    render();
  }

  /* ---------------- Page turning ---------------- */

  function makeLeaf(dir, frontIdx, backIdx) {
    const leaf = el('div', 'leaf ' + dir);
    const front = el('div', 'face front');
    const back = el('div', 'face back');
    front.appendChild(renderPage(story, frontIdx));
    back.appendChild(renderPage(story, backIdx));
    front.appendChild(el('div', 'shade'));
    back.appendChild(el('div', 'shade'));
    leaf.append(front, back);
    return leaf;
  }

  function turn(dir) {
    if (turning) return;
    if (dir > 0 && !canNext()) return;
    if (dir < 0 && !canPrev()) return;
    turning = true;

    let leaf, after;
    if (mode === 'spread') {
      if (dir > 0) {
        leaf = makeLeaf('fwd', cur, cur + 1);
        fill(pageR, story, cur + 2);            // what is revealed underneath
        after = () => { cur += 2; };
      } else {
        leaf = makeLeaf('back', cur - 1, cur - 2);
        fill(pageL, story, cur - 3);
        after = () => { cur -= 2; };
      }
    } else {
      if (dir > 0) {
        leaf = makeLeaf('fwd', cur, cur + 1);
        fill(pageR, story, cur + 1);
        after = () => { cur += 1; };
      } else {
        leaf = makeLeaf('back', cur - 1, cur - 1);
        after = () => { cur -= 1; };
      }
    }
    book.appendChild(leaf);

    let done = false;
    const finish = () => {
      if (done) return;
      done = true;
      after();
      leaf.remove();
      turning = false;
      render();
    };
    leaf.addEventListener('transitionend', (e) => { if (e.target === leaf) finish(); });
    setTimeout(finish, 800);                      // safety net if transitionend never fires
    // force layout so the transition runs from the starting transform
    void leaf.offsetWidth;
    requestAnimationFrame(() => leaf.classList.add('go'));
  }

  /* ---------------- Layout / sizing ---------------- */

  function layout() {
    const vw = window.innerWidth, vh = window.innerHeight;
    const narrow = vw < 700 || vw < vh * 1.05;
    const newMode = narrow ? 'single' : 'spread';
    const navW = vw <= 520 ? 0 : 108;
    const availW = vw - navW - 24;
    const availH = vh - 70;
    let w;
    if (newMode === 'spread') w = Math.min(availW / 2, availH * 0.75);
    else w = Math.min(availW, availH * 0.75);
    w = Math.floor(w);
    document.documentElement.style.setProperty('--page-w', w + 'px');
    document.documentElement.style.setProperty('--page-h', Math.floor(w * 4 / 3) + 'px');

    if (newMode !== mode) {
      const shown = mode === 'spread' ? Math.max(0, cur - 1) : cur;   // keep the reader on the same page
      mode = newMode;
      book.classList.toggle('spread', mode === 'spread');
      book.classList.toggle('single', mode === 'single');
      cur = mode === 'spread' ? spreadRight(shown) : shown;
    }
    applyScale(computeScale(story, book));
    render();
  }

  function applyScale(scale) {
    fsScale = scale;
    book.style.setProperty('--fs-scale', scale);
  }

  // Re-measure after fonts or images load, and re-render only if the scale changed.
  let refitQueued = false;
  function scheduleRefit() {
    if (refitQueued) return;
    refitQueued = true;
    setTimeout(() => {                 // not rAF: that never fires in a hidden tab
      refitQueued = false;
      const scale = computeScale(story, book);
      if (scale !== fsScale && !turning) { applyScale(scale); render(); }
      else if (scale !== fsScale) applyScale(scale);
    }, 0);
  }
  // The web font usually arrives after the first layout and is wider than the
  // fallback, so re-measure once it lands (and again on full page load).
  if (document.fonts) {
    document.fonts.addEventListener('loadingdone', scheduleRefit);
    // Explicitly request the face so the promise resolves only once it is usable.
    document.fonts.load('1em "Libre Baskerville"').then(scheduleRefit, () => {});
    document.fonts.ready.then(scheduleRefit);
  }
  window.addEventListener('load', () => { scheduleRefit(); setTimeout(scheduleRefit, 1500); });

  /* ---------------- Input ---------------- */

  // Readers can select and copy the text, so a click that starts, extends,
  // or clears a selection must not turn the page.
  const hasSelection = () => {
    const sel = window.getSelection();
    return !!sel && !sel.isCollapsed && sel.toString().length > 0;
  };
  let hadSelection = false;

  book.addEventListener('click', (e) => {
    const li = e.target.closest('[data-goto]');
    if (li) { goTo(+li.dataset.goto); return; }
    if (e.target.closest('a[href]')) return;
    if (hasSelection() || hadSelection) { hadSelection = false; return; }
    const r = book.getBoundingClientRect();
    turn(e.clientX - r.left < r.width / 2 ? -1 : 1);
  });
  btnPrev.addEventListener('click', () => turn(-1));
  btnNext.addEventListener('click', () => turn(1));

  window.addEventListener('keydown', (e) => {
    if (e.metaKey || e.ctrlKey || e.altKey) return;
    if (e.target.closest && e.target.closest('input')) return;   // typing a page number
    switch (e.key) {
      case 'g': case 'G': e.preventDefault(); openJump(); break;
      case 'ArrowRight': case 'ArrowDown': case 'PageDown': case ' ': case 'Enter': e.preventDefault(); turn(1); break;
      case 'ArrowLeft': case 'ArrowUp': case 'PageUp': case 'Backspace': e.preventDefault(); turn(-1); break;
      case 'Home': goTo(0); break;
      case 'End': goTo(N - 1); break;
    }
  });

  // swipe
  let sx = null, sy = null;
  book.addEventListener('pointerdown', (e) => {
    hadSelection = hasSelection();
    sx = e.clientX; sy = e.clientY;
  });
  book.addEventListener('pointerup', (e) => {
    if (sx == null) return;
    const dx = e.clientX - sx, dy = e.clientY - sy;
    sx = sy = null;
    // A mouse drag across the page selects text; only touch and pen swipe.
    if (e.pointerType === 'mouse' || hasSelection()) return;
    if (Math.abs(dx) > 50 && Math.abs(dx) > Math.abs(dy) * 1.5) {
      turn(dx < 0 ? 1 : -1);
      e.stopImmediatePropagation();
      suppressClick = true;
    }
  });
  let suppressClick = false;
  book.addEventListener('click', (e) => { if (suppressClick) { suppressClick = false; e.stopImmediatePropagation(); } }, true);

  window.addEventListener('resize', layout);
  window.addEventListener('orientationchange', layout);
  if (window.visualViewport) window.visualViewport.addEventListener('resize', layout);
  window.addEventListener('hashchange', () => {
    const m = location.hash.match(/^#p(\d+)$/);
    if (m && !turning) goTo(+m[1]);
  });

  /* ---------------- Start ---------------- */

  // A bare URL always opens on the cover; "#p7" opens page 7.
  const hash = location.hash.match(/^#p(\d+)$/);
  cur = clamp(hash ? +hash[1] : 0);
  layout();
})();
