// Generated by tools/make-web-images.py - pixel size of each web illustration.
window.IMAGE_SIZES = {
  "illustrations/web/1-FAT-title-final.webp": [
    1487,
    1800
  ],
  "illustrations/web/10-FAT-find-notes-final.webp": [
    1008,
    1400
  ],
  "illustrations/web/11-FAT-cookies-flashback-final.webp": [
    1400,
    1076
  ],
  "illustrations/web/12-FAT-cake-final copy.webp": [
    1400,
    1287
  ],
  "illustrations/web/2-FAT-Meet-HF-final.webp": [
    1083,
    1400
  ],
  "illustrations/web/3-FAT-Machines-Sandboxes-final.webp": [
    1400,
    1039
  ],
  "illustrations/web/4-FAT-shed-note-final.webp": [
    1400,
    1045
  ],
  "illustrations/web/5-FAT-shed-hole-final.webp": [
    1400,
    1051
  ],
  "illustrations/web/6-FAT-shed-return-final.webp": [
    1400,
    1051
  ],
  "illustrations/web/7-FAT-keys-fina.webp": [
    1400,
    1058
  ],
  "illustrations/web/8-FAT-break-in-final.webp": [
    1400,
    1064
  ],
  "illustrations/web/9-FAT-HF-yelling-final.webp": [
    1400,
    1050
  ]
};
