#!/usr/bin/env python3
"""Build the web copies of the illustrations.

Reads the master PNGs in illustrations/ (the numbered story art) and writes,
for each one, illustrations/web/<name>.webp plus illustrations/web/sizes.js.

The web copies are downscaled, and their white is turned into transparency
using the same arithmetic as a multiply blend, so the page's paper colour and
texture show through the margins without any blending at render time.

sizes.js records each copy's pixel size so the reader can lay pages out
before the pictures arrive (and measure text pages without fetching them).

Run it again whenever a master changes:  python3 tools/make-web-images.py
"""
import glob, json, os, re, sys
from PIL import Image
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, 'illustrations')
OUT_DIR = os.path.join(SRC_DIR, 'web')
COVER_MAX = 1800     # the cover fills a whole page, so it gets more pixels
INLINE_MAX = 1400    # story pictures sit above text at well under half a page
QUALITY = 85
SKIP = ('13-', '14-')   # favicon and social-card sources are not story pages

def white_to_alpha(im):
    a = np.asarray(im.convert('RGB')).astype(np.float32) / 255.0
    m = a.min(axis=2, keepdims=True)          # the "white" component of each pixel
    alpha = 1.0 - m                           # pure white -> fully transparent
    safe = np.where(alpha > 1e-4, alpha, 1.0)
    rgb = np.where(alpha > 1e-4, np.clip((a - m) / safe, 0, 1), 0)
    out = np.concatenate([rgb, alpha], axis=2)
    return Image.fromarray((out * 255 + 0.5).astype(np.uint8), 'RGBA')

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    sizes = {}
    for path in sorted(glob.glob(os.path.join(SRC_DIR, '*.png'))):
        name = os.path.basename(path)
        if not re.match(r'\d+-', name) or name.startswith(SKIP):
            continue
        im = Image.open(path)
        limit = COVER_MAX if name.startswith('1-') else INLINE_MAX
        im.thumbnail((limit, limit), Image.LANCZOS)
        out = white_to_alpha(im)
        stem = os.path.splitext(name)[0]
        dst = os.path.join(OUT_DIR, stem + '.webp')
        out.save(dst, quality=QUALITY, alpha_quality=90, method=6)
        rel = 'illustrations/web/' + stem + '.webp'
        sizes[rel] = list(out.size)
        print(f'{rel}: {out.size[0]}x{out.size[1]} {os.path.getsize(dst) / 1e6:.2f} MB')
    with open(os.path.join(OUT_DIR, 'sizes.js'), 'w') as f:
        f.write('// Generated by tools/make-web-images.py - pixel size of each web illustration.\n')
        f.write('window.IMAGE_SIZES = ' + json.dumps(sizes, indent=2) + ';\n')
    print('wrote sizes.js with', len(sizes), 'entries')

if __name__ == '__main__':
    sys.exit(main())
