#!/usr/bin/env python3
"""Build the web copies of the illustrations.

Reads the master PNGs in illustrations/ (the numbered story art) and writes,
for each one, illustrations/web/<name>.webp plus illustrations/web/sizes.js.

The web copies are downscaled, and their white is turned into transparency
using the same arithmetic as a multiply blend, so the page's paper colour and
texture show through the margins without any blending at render time.

sizes.js records each copy's pixel size so the reader can lay pages out
before the pictures arrive (and measure text pages without fetching them).

The cover art (the master starting "1-") also gets illustrations/web/
cover-1200.avif and cover-1600.avif, which the closed book shows: its WebP
copy printed onto the cover stock (multiplied onto its cream, so they're
opaque and need no blending), encoded with avifenc (from libavif: brew
install libavif) if it's installed, else skipped. It also prints a tiny copy
of the cover as a data: URI, the blurred placeholder shown until the art
arrives; paste it into COVER_PLACEHOLDER in reader.js when the cover changes.

Run it again whenever a master changes:  python3 tools/make-web-images.py
"""
import base64, glob, io, json, os, re, shutil, subprocess, sys, tempfile
from PIL import Image
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, 'illustrations')
OUT_DIR = os.path.join(SRC_DIR, 'web')
COVER_MAX = 1800     # the cover fills a whole page, so it gets more pixels
INLINE_MAX = 1400    # story pictures sit above text at well under half a page
QUALITY = 85
SKIP = ('13-', '14-')   # favicon and social-card sources are not story pages
COVER_STOCK = (0xf5, 0xee, 0xdd)   # the cover's paper, --paper in reader.css
COVER_WIDTHS = (1200, 1600)        # the cover AVIFs; see the preload in index.html
AVIFENC_ARGS = ['-q', '50', '-s', '4', '-d', '12']   # 12-bit: smaller at the same quality
PLACEHOLDER_WIDTH = 24

def white_to_alpha(im):
    a = np.asarray(im.convert('RGB')).astype(np.float32) / 255.0
    m = a.min(axis=2, keepdims=True)          # the "white" component of each pixel
    alpha = 1.0 - m                           # pure white -> fully transparent
    safe = np.where(alpha > 1e-4, alpha, 1.0)
    rgb = np.where(alpha > 1e-4, np.clip((a - m) / safe, 0, 1), 0)
    out = np.concatenate([rgb, alpha], axis=2)
    return Image.fromarray((out * 255 + 0.5).astype(np.uint8), 'RGBA')

def on_cover_stock(web, width):
    """The (transparent) web copy at the given width, printed onto the cover
    stock: as if multiplied onto it."""
    flat = Image.new('RGB', web.size, 'white')
    flat.paste(web, mask=web.getchannel('A'))
    flat = flat.resize((width, round(web.height * width / web.width)), Image.LANCZOS)
    a = np.asarray(flat).astype(np.float32) * (np.array(COVER_STOCK, np.float32) / 255.0)
    return Image.fromarray((a + 0.5).astype(np.uint8), 'RGB')

def make_cover(web):
    avifenc = shutil.which('avifenc')
    if not avifenc:
        print('skipped the cover AVIFs: avifenc not found (brew install libavif)')
    else:
        with tempfile.TemporaryDirectory() as tmp:
            for width in COVER_WIDTHS:
                png = os.path.join(tmp, f'cover-{width}.png')
                on_cover_stock(web, width).save(png)
                dst = os.path.join(OUT_DIR, f'cover-{width}.avif')
                subprocess.run([avifenc, *AVIFENC_ARGS, png, dst], check=True, stdout=subprocess.DEVNULL)
                print(f'illustrations/web/cover-{width}.avif: {os.path.getsize(dst) / 1e3:.0f} KB')
    buf = io.BytesIO()
    on_cover_stock(web, PLACEHOLDER_WIDTH).save(buf, 'WEBP', quality=60, method=6)
    print('cover placeholder (COVER_PLACEHOLDER in reader.js):')
    print('data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode())

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    sizes = {}
    for path in sorted(glob.glob(os.path.join(SRC_DIR, '*.png'))):
        name = os.path.basename(path)
        if not re.match(r'\d+-', name) or name.startswith(SKIP):
            continue
        im = Image.open(path)
        limit = COVER_MAX if name.startswith('1-') else INLINE_MAX
        im.thumbnail((limit, limit), Image.LANCZOS)
        out = white_to_alpha(im)
        stem = os.path.splitext(name)[0]
        dst = os.path.join(OUT_DIR, stem + '.webp')
        out.save(dst, quality=QUALITY, alpha_quality=90, method=6)
        rel = 'illustrations/web/' + stem + '.webp'
        sizes[rel] = list(out.size)
        print(f'{rel}: {out.size[0]}x{out.size[1]} {os.path.getsize(dst) / 1e6:.2f} MB')
        if name.startswith('1-'):
            make_cover(Image.open(dst))
    with open(os.path.join(OUT_DIR, 'sizes.js'), 'w') as f:
        f.write('// Generated by tools/make-web-images.py - pixel size of each web illustration.\n')
        f.write('window.IMAGE_SIZES = ' + json.dumps(sizes, indent=2) + ';\n')
    print('wrote sizes.js with', len(sizes), 'entries')

if __name__ == '__main__':
    sys.exit(main())
